# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:latest

pipelines:
  default:
    - step:
        caches:
          - node
          - docker
        script: # Modify the commands below to build your repository.
          - npm install
          - npm install -g snyk
          - snyk auth $SNYK_TOKEN
          - snyk code test --sarif > snykcode_results.sarif || true         
          - docker build -t snykschmidtty/goof:latest .
          - pipe: snyk/snyk-scan:0.5.1
            variables:
              SNYK_TOKEN: $SNYK_TOKEN
              LANGUAGE: "npm"
              DONT_BREAK_BUILD: "true"
              MONITOR: "true"
              CODE_INSIGHTS_RESULTS: "true"
              EXTRA_ARGS: "--project-name=goof-bitbucket-pipelines --remote-repo-url=goof-bitbucket-pipelines"
          - pipe: snyk/snyk-scan:0.5.1
            variables:
              SNYK_TOKEN: $SNYK_TOKEN
              LANGUAGE: "docker"
              IMAGE_NAME: "snykschmidtty/goof:latest"
              DONT_BREAK_BUILD: "true"
              MONITOR: "true"
              EXTRA_ARGS: "--project-name=docker-image|goof-bitbucket-pipelines --app-vulns"
        artifacts:
          download: true
          paths:
            - snykcode_results.sarif
