name: "Snyk Container Scan"

on:
  push:
    branches:
    - master

jobs:
  snyk_container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build image
      env:
        DOCKER_BUILDKIT: 1
      run: docker build -t goof-github-actions .
    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        #command: monitor
        image: goof-github-actions
        args: --file=Dockerfile
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif
    - name: Snyk Monitor
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with: 
        command: monitor
        image: goof-github-actions
        args: --file=Dockerfile --project-name=docker-image|goof-github-actions --app-vulns --project-environment=frontend --project-lifecycle=production --project-business-criticality=high --project-tags=CI=GithubActions,PCI=yes
  #snyk_monitor:
   # runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@master
    #- name: Run Snyk to check Docker image for vulnerabilities
      #continue-on-error: true
      #uses: snyk/actions/docker@master
      #env:
        #SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #with:
        #command: monitor
        #image: goof-github-actions
        #args: --file=Dockerfile --project-name=docker-image|goof-github-actions
